services:
  backend:
    build: backend
    ports:
      - 8080:8081
    environment:
      - POSTGRES_DB=my_database
    networks:
      - spring-postgres
    depends_on:
      - db
  frontend:
    image: nginx:alpine
    container_name: angular-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./createinit.sql:/docker-entrypoint-initdb.d/createinit.sql
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=my_database
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  spring-postgres:
